- name: Download package-query PKGBUILD
  get_url:
    url: https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=package-query
    dest: /tmp/pqPKG
    mode: 0440

- name: Build and Install package-query
  command: makepkg -si --noconfirm -p /tmp/pqPKG
  args:
    chdir: /tmp

- name: Download yaourt PKGBUILD
  get_url:
    url: https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=yaourt
    dest: /tmp/yPKG
    mode: 0440

- name: Build and Install yaourt
  command: makepkg -si --noconfirm -p /tmp/yPKG
  args:
    chdir: /tmp

- name: Install lib-tbb
  command: yaourt -S --noconfirm intel-tbb --needed

- name: /tmp clean-up
  file:
    path: /tmp
    state: absent
  ignore_errors: yes
