- name: Generate wpa_supplicant-wlan0.conf
  command: wpa_passphrase "{{SSID}}" "{{PASSWD}}"
  register: wpa

- copy: content="{{wpa.stdout}}" dest=/etc/wpa_supplicant/wpa_supplicant-wlan0.conf
  become: true

- name: Enable wpa_supplicant@wlan0
  command: systemctl enable wpa_supplicant@wlan0
  become: true

- name: Copy wlan0.network
  copy:
    src: wlan0.network
    dest: /etc/systemd/network/
  become: true
