- name: Set authorized key from GitHub
  authorized_key:
    user: alarm
    state: present
    key: https://github.com/phedoreanu.keys

- name: Update, upgrade & install
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install group base-devel
  pacman:
    name: base-devel
    state: present
  become: true

- name: Install stuff
  command: |
    pacman -Syu --noconfirm --needed --noprogressbar
      bash-completion vim htop
  become: true

- name: Set CH Timezone
  command: timedatectl set-timezone Europe/Zurich
  become: true
