- name: Set authorized key from GitHub
  authorized_key:
    user: alarm
    state: present
    key: https://github.com/{{github_username}}.keys

- name: Update, upgrade & install
  pacman:
    update_cache: yes
    upgrade: yes
  become: true

- name: Install group base-devel
  pacman:
    name: base-devel
    state: present
  become: true

- name: Install bash-completion
  command: |
    pacman -Syu --noconfirm --needed --noprogressbar
      bash-completion
  become: true

- name: Set CH Timezone
  command: timedatectl set-timezone Europe/Zurich
  become: true

- name: Disable overscan
  lineinfile:
    path: /boot/config.txt
    line: '{{item}}'
  with_items:
    - 'disable_overscan=1'
  become: true
