- name: Install Docker
  pacman:
    name: docker
    state: present
  become: true

- name: Enable docker daemon
  command: systemctl enable docker.service
  become: true

- name: Add alarm to docker group
  command: gpasswd -a alarm docker
  become: true
